keras Bsics

In [1]:
import numpy as np 

In [3]:
# Reading datasets 
from numpy import genfromtxt
data = genfromtxt('bank_note_data.txt', delimiter=',')

In [6]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [7]:
labels = data[:,4]

In [9]:
features = data[:,0:4]

In [11]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [12]:
X = features
y = labels

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train , X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [16]:
X_train

array([[-0.56877,  1.4174 , -1.4252 , -1.1246 ],
       [ 0.47368,  3.3605 , -4.5064 , -4.0431 ],
       [ 1.0652 ,  8.3682 , -1.4004 , -1.6509 ],
       ...,
       [-7.0364 ,  9.2931 ,  0.16594, -4.5396 ],
       [-3.4605 ,  2.6901 ,  0.16165, -1.0224 ],
       [-3.3582 , -7.2404 , 11.4419 , -0.57113]])

In [20]:
X_test.shape

(412, 4)

In [21]:
y_train

array([1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 0.

Standardizing the Data

In [22]:
from sklearn.preprocessing import MinMaxScaler

In [23]:
scaler_object = MinMaxScaler()

In [24]:
scaler_object.fit(X_train)

MinMaxScaler()

In [25]:
scaled_X_train = scaler_object.transform(X_train)

In [26]:
scaled_X_test = scaler_object.transform(X_test)

In [27]:
X_train.max()

17.9274

In [28]:
scaled_X_train.max()

1.0000000000000002

In [29]:
X_train

array([[-0.56877,  1.4174 , -1.4252 , -1.1246 ],
       [ 0.47368,  3.3605 , -4.5064 , -4.0431 ],
       [ 1.0652 ,  8.3682 , -1.4004 , -1.6509 ],
       ...,
       [-7.0364 ,  9.2931 ,  0.16594, -4.5396 ],
       [-3.4605 ,  2.6901 ,  0.16165, -1.0224 ],
       [-3.3582 , -7.2404 , 11.4419 , -0.57113]])

In [30]:
scaled_X_train

array([[4.66818828e-01, 5.68406755e-01, 1.65429714e-01, 6.93101291e-01],
       [5.41994245e-01, 6.41114774e-01, 3.25546495e-02, 4.20616766e-01],
       [5.84651220e-01, 8.28495736e-01, 1.66499200e-01, 6.43963513e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

Building the Network with keras

In [32]:
from keras.models import Sequential
from keras.layers import Dense

In [34]:
model = Sequential()

model.add(Dense(4, input_dim = 4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/home/cfdml-04/miniconda3/envs/myenv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2025-03-10 14:29:40.050595: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


Compile Model 

In [35]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [36]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
30/30 - 1s - 18ms/step - accuracy: 0.3604 - loss: 0.7090
Epoch 2/50
30/30 - 0s - 1ms/step - accuracy: 0.5250 - loss: 0.6930
Epoch 3/50
30/30 - 0s - 1ms/step - accuracy: 0.6240 - loss: 0.6814
Epoch 4/50
30/30 - 0s - 2ms/step - accuracy: 0.6490 - loss: 0.6717
Epoch 5/50
30/30 - 0s - 1ms/step - accuracy: 0.6677 - loss: 0.6620
Epoch 6/50
30/30 - 0s - 1ms/step - accuracy: 0.6615 - loss: 0.6521
Epoch 7/50
30/30 - 0s - 1ms/step - accuracy: 0.6552 - loss: 0.6416
Epoch 8/50
30/30 - 0s - 1ms/step - accuracy: 0.6594 - loss: 0.6289
Epoch 9/50
30/30 - 0s - 1ms/step - accuracy: 0.6625 - loss: 0.6152
Epoch 10/50
30/30 - 0s - 1ms/step - accuracy: 0.6885 - loss: 0.6000
Epoch 11/50
30/30 - 0s - 1ms/step - accuracy: 0.7052 - loss: 0.5834
Epoch 12/50
30/30 - 0s - 1ms/step - accuracy: 0.7219 - loss: 0.5667
Epoch 13/50
30/30 - 0s - 1ms/step - accuracy: 0.7344 - loss: 0.5502
Epoch 14/50
30/30 - 0s - 1ms/step - accuracy: 0.7417 - loss: 0.5340
Epoch 15/50
30/30 - 0s - 1ms/step - accuracy: 0.7573 - l

Predicting New Unseen data

In [37]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.51963164, 0.38970316, 0.28618249, 0.92478549],
       [0.68099575, 0.57607382, 0.35760953, 0.86502189],
       [0.72424262, 0.73286884, 0.13069728, 0.73596217]])

In [39]:
model.predict(scaled_X_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


array([[0.04755585],
       [0.46452254],
       [0.28299367],
       [0.06583225],
       [0.04151516],
       [0.01656942],
       [0.16968454],
       [0.01121317],
       [0.02935722],
       [0.10404889],
       [0.5400883 ],
       [0.89795905],
       [0.1379179 ],
       [0.84080684],
       [0.56109315],
       [0.29940894],
       [0.9288641 ],
       [0.9366548 ],
       [0.9020659 ],
       [0.8624618 ],
       [0.02623327],
       [0.06122775],
       [0.87668014],
       [0.0187581 ],
       [0.9891024 ],
       [0.01801727],
       [0.01194089],
       [0.8870646 ],
       [0.00772169],
       [0.00850726],
       [0.79992175],
       [0.08704843],
       [0.14008717],
       [0.98892033],
       [0.9802533 ],
       [0.01297368],
       [0.5063253 ],
       [0.8275869 ],
       [0.91374594],
       [0.07297159],
       [0.04464336],
       [0.7956457 ],
       [0.8351283 ],
       [0.03163562],
       [0.98405844],
       [0.88972276],
       [0.9612577 ],
       [0.030

Evaluating Model Performance

In [40]:
model.metrics_names

['loss', 'compile_metrics']

In [41]:
model.evaluate(x = scaled_X_test, y= y_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9392 - loss: 0.1690 


[0.14549168944358826, 0.958737850189209]

In [42]:
from sklearn.metrics import confusion_matrix, classification_report

In [55]:
predictions = np.argmax(model.predict(scaled_X_test), axis=-1)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


In [48]:
confusion_matrix(y_test, predictions)

array([[229,   0],
       [183,   0]])

In [49]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.56      1.00      0.71       229
         1.0       0.00      0.00      0.00       183

    accuracy                           0.56       412
   macro avg       0.28      0.50      0.36       412
weighted avg       0.31      0.56      0.40       412



/home/cfdml-04/miniconda3/envs/myenv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/cfdml-04/miniconda3/envs/myenv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/cfdml-04/miniconda3/envs/myenv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.cap

Solving and LOading Models

In [51]:
model.save('myfirstmodel.h5')

In [52]:
from keras.models import load_model

In [53]:
newmodel = load_model('myfirstmodel.h5')

In [57]:
newmodel.predict(X_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


array([[1.33587474e-09],
       [9.99999881e-01],
       [9.99983609e-01],
       [1.55874656e-15],
       [5.62865054e-03],
       [1.47780271e-15],
       [1.91248559e-10],
       [1.01851045e-11],
       [7.28985218e-14],
       [2.02977402e-14],
       [9.99045968e-01],
       [9.99974549e-01],
       [3.00073131e-19],
       [9.99999881e-01],
       [1.21425934e-14],
       [9.99999404e-01],
       [9.99999940e-01],
       [9.99999940e-01],
       [9.99692380e-01],
       [9.99922454e-01],
       [1.61951385e-03],
       [2.09449857e-17],
       [9.99999225e-01],
       [5.12444058e-06],
       [1.00000000e+00],
       [3.31378869e-10],
       [5.89644241e-15],
       [1.00000000e+00],
       [2.75642997e-09],
       [3.40943614e-12],
       [9.99998629e-01],
       [7.75534134e-15],
       [1.89489741e-14],
       [1.00000000e+00],
       [1.00000000e+00],
       [5.52382640e-10],
       [9.99214470e-01],
       [9.98714626e-01],
       [9.99992013e-01],
       [5.04157102e-15],


In [58]:
# Done